### ISSUE TITLE
Unable to resolve module `react-native/Libraries/StyleSheet/ColorPropType.js`

### ISSUE THREAD

**Issue by topwebtek7** [react-native-linear-gradient/react-native-linear-gradient#356]
Unable to resolve module `react-native/Libraries/StyleSheet/ColorPropType.js` in `react-native-linear-gradient/index.ios.js` and `react-native-linear-gradient/index.android.js` with latest React-Native v0.57.3

**Comment by radex** [comment]
works for me. are you sure you don't have some stale yarn cache or something?

**Comment by topwebtek7** [comment]
It works now. Thanks for fixing

**Comment by radex** [comment]
I didn't do anything 😂

**Comment by mjmasn** [comment]
@radex in `react-native@0.58-rc.0` that file has been moved to `Libraries/DeprecatedPropTypes/DeprecatedColorPropType.js`. Might need some conditional require to work with old and new versions :thinking:

**Comment by mjmasn** [comment]
ah, just saw the PR to remove the prop types, ignore me :)

**Comment by nwaughachukwuma** [comment]
Hey guys, @topwebtek and @radex, am having this issue in version 0.58.0 and have not been able to fix it. What could be responsible? I have done `npm start -- --reset-cache` yet, error persists. Any help will be appreciated

**Comment by frodoe7** [comment]
@nwaughachukwuma 

copy from this file 

> /node_modeuls/react-native/Libraries/DeprecatedPropTypes/DeprecatedColorPropType.js 

to this location
> /node_modeuls/react-native/Libraries/StyleSheet/

then rename it to ColorPropType.js

this should fix the issue

**Comment by nwaughachukwuma** [comment]
OK thanks so much. But the problem is that I dont build locally. I use app center to automate my build process

**Comment by dlferro** [comment]
Definitely not a long term fix.

**Comment by nwaughachukwuma** [comment]
Yeah, there's a lot of bugs in React Native 0.58.x (x<=3), and I raised an issue over that. Let's hope it becomes stable in the near future. Thanks so much

**Comment by KevinColemanInc** [comment]
@radex Should this issue be re-opened? That module has been deprecated.

**Comment by radex** [comment]
@KevinColemanInc You're right. PropTypes are dead, long live Flow types.

I started doing the work to remove PropTypes from this library in this PR: https://github.com/react-native-community/react-native-linear-gradient/pull/364/files

… but I don't have the time right now to finish it. @KevinColemanInc @nwaughachukwuma @Nualiian  @dlferro  @frodoe7 Is any of you willing to pick up the work? There's not much to do there… just clean up and test on iOS and Android that nothing is broken. Then we can merge it and release and update that will fix it once and for all

**Comment by voidstarfire** [comment]
Flow and PropTypes are dead. TypeScript is where it's at.

Anyhow, do we have a temporary fix that would fix build servers? Cannot copy stuff manually.
We updated 3 apps to 58 today :-|

**Comment by radex** [comment]
@voidstarfire See the comment above. The fix is fairly straightforward — remove PropTypes altogether and copy over updated Flow types (see #364). Please send a qiuck PR and I will merge and release today if it looks good :)

**Comment by voidstarfire** [comment]
Heya thanks for the reply.

Production pipelines do things from scratch (IE, yarn install), I'd have to create a little script and add it to multiple steps :-D a lotta work. I just downgraded for now, RN 57.

I'm glad there's a PR waiting great :-)

**Comment by NrqhEIcsRi004** [comment]
With the update of RN, I hope to solve this problem as soon as possible.

**Comment by curiousdustin** [comment]
I'm having this issue as well. Is there still not a fix that doesn't require messing around with the `react-native` module files?

**Comment by csouth3** [comment]
Yes, I'm eagerly anticipating this fix as well.

**Comment by curiousdustin** [comment]
This error disappeared once I upgraded to **react-native 0.59.4** and **react-native-linear-gradient 2.5.4**

Should this be closed?

**Comment by csouth3** [comment]
Looks like 2.5.4 works for me too

**Comment by mimamuh** [comment]
Some for me, updated `react-native-linear-gradient 2.4.4` to `react-native-linear-gradient 2.5.4` and it works again.

**Comment by ziaulrehman40** [comment]
Updating to 2.5.4 hanged my error to:

```
error: bundling failed: Error: Unable to resolve module `./nativeLinearGradient` from `/Users/.../node_modules/react-native-linear-gradient/index.ios.js`: The module `./nativeLinearGradient` could not be found from `/Users/.../node_modules/react-native-linear-gradient/index.ios.js`. Indeed, none of these files exist:
  * `/Users/.../node_modules/react-native-linear-gradient/nativeLinearGradient(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/.../node_modules/react-native-linear-gradient/nativeLinearGradient/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/.../node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/.../node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/.../node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/.../node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

**Comment by rnowm** [comment]
I'm still seeing this issue with react-native: 0.59.9 and react-native-linear-gradient: 2.5.4

**Comment by lp4298707** [comment]
> Updating to 2.5.4 changed my error to:
> 
> ```
> error: bundling failed: Error: Unable to resolve module `./nativeLinearGradient` from `/Users/.../node_modules/react-native-linear-gradient/index.ios.js`: The module `./nativeLinearGradient` could not be found from `/Users/.../node_modules/react-native-linear-gradient/index.ios.js`. Indeed, none of these files exist:
>   * `/Users/.../node_modules/react-native-linear-gradient/nativeLinearGradient(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
>   * `/Users/.../node_modules/react-native-linear-gradient/nativeLinearGradient/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
>     at ModuleResolver.resolveDependency (/Users/.../node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
>     at ResolutionRequest.resolveDependency (/Users/.../node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
>     at DependencyGraph.resolveDependency (/Users/.../node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
>     at Object.resolve (/Users/.../node_modules/metro/src/lib/transformHelpers.js:261:42)
>     at dependencies.map.result (/Users/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
>     at Array.map (<anonymous>)
>     at resolveDependencies (/Users/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
>     at /Users/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (/Users/.../node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
> ```

edit index.android.js and save , or delete all content of the index.android.js and recover , i fixed it
