### ISSUE TITLE
not working in web

### ISSUE THREAD

**Issue by learncodingforweb** [react-native-linear-gradient/react-native-linear-gradient#523]
ERROR in ./node_modules/react-native-linear-gradient/index.android.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/box/dev/rn_web/node_modules/react-native-linear-gradient/index.android.js: Unexpected token, expected "," (8:36)

   6 | import { processColor, StyleSheet, View } from 'react-native';
   7 |
>  8 | import NativeLinearGradient, { type Props } from './common';
     |                                     ^
   9 |
  10 | const convertPoint = (name, point) => {
  11 |   if (Array.isArray(point)) {
    at Object._raise (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:775:17)
    at Object.raiseWithData (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:768:17)
    at Object.raise (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:736:17)
    at Object.unexpected (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:9699:16)
    at Object.expect (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:9685:28)
    at Object.parseNamedImportSpecifiers (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:13789:14)
    at Object.parseImport (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:13624:39)
    at Object.parseStatementContent (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:12315:27)
    at Object.parseStatement (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:12215:17)
    at Object.parseBlockOrModuleBlockBody (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:12795:25)
 @ ./node_modules/react-native-linear-gradient/index.js 3:0-55 4:65-86

ERROR in ./node_modules/react-native-linear-gradient/index.ios.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /home/box/dev/rn_web/node_modules/react-native-linear-gradient/index.ios.js: Unexpected token, expected "," (8:36)

   6 | import { processColor, View } from 'react-native';
   7 |
>  8 | import NativeLinearGradient, { type Props } from './common';
     |                                     ^
   9 |
  10 | const convertPoint = (name, point) => {
  11 |   if (Array.isArray(point)) {
    at Object._raise (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:775:17)
    at Object.raiseWithData (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:768:17)
    at Object.raise (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:736:17)
    at Object.unexpected (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:9699:16)
    at Object.expect (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:9685:28)
    at Object.parseNamedImportSpecifiers (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:13789:14)
    at Object.parseImport (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:13624:39)
    at Object.parseStatementContent (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:12315:27)
    at Object.parseStatement (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:12215:17)
    at Object.parseBlockOrModuleBlockBody (/home/box/dev/rn_web/node_modules/@babel/parser/lib/index.js:12795:25)
 @ ./node_modules/react-native-linear-gradient/index.js 2:0-47 4:45-62

**Comment by Nirmal-cod** [comment]
Facing similar issue.

**Comment by GolfredoPerezFernandez** [comment]
+1

**Comment by Buwaneka-Sumanasekara** [comment]
try to use this `https://www.npmjs.com/package/react-native-web-linear-gradient`

**Comment by kidar2** [comment]
+1

**Comment by SDanDyS** [comment]
The error persists.
